export const DummyClientsSeed = [
  { firstName: 'Rosa', lastName: 'Schwieso', email: 'rschwieso0@irs.gov', gender: 'Female', dni: '512-75-1374', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Dionisio', lastName: 'Digges', email: 'ddigges1@google.co.uk', gender: 'Male', dni: '833-10-5373', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Pippa', lastName: 'Portugal', email: 'pportugal2@census.gov', gender: 'Female', dni: '885-90-8391', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Inglis', lastName: 'Coulman', email: 'icoulman3@paginegialle.it', gender: 'Male', dni: '245-40-6623', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Susi', lastName: 'Sykora', email: 'ssykora4@mtv.com', gender: 'Female', dni: '298-91-6534', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Eloise', lastName: 'Wessell', email: 'ewessell5@comcast.net', gender: 'Female', dni: '253-38-9125', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Darill', lastName: 'Bretherton', email: 'dbretherton6@addtoany.com', gender: 'Male', dni: '837-23-2225', comments: '', createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Lonna', lastName: 'Godard', email: 'lgodard7@wufoo.com', gender: 'Female', dni: '320-77-7196', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Theobald', lastName: 'Sopp', email: 'tsopp8@whitehouse.gov', gender: 'Male', dni: '851-64-4304', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Crystal', lastName: 'Graveney', email: 'cgraveney9@netvibes.com', gender: 'Female', dni: '321-94-6332', comments: 'potenti', createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Victor', lastName: 'McGrill', email: 'vmcgrilla@last.fm', gender: 'Male', dni: '826-65-8818', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Jami', lastName: 'Siviter', email: 'jsiviterb@china.com.cn', gender: 'Female', dni: '438-99-7795', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Garnette', lastName: 'McElhargy', email: 'gmcelhargyc@bizjournals.com', gender: 'Female', dni: '515-31-9893', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Cassy', lastName: 'Fadell', email: 'cfadelld@typepad.com', gender: 'Female', dni: '874-99-9435', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Keen', lastName: 'Woolstenholmes', email: 'kwoolstenholmese@elegantthemes.com', gender: 'Male', dni: '321-62-5673', comments: 'pretium nisl ut volutpat sapien arcu sed', createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Trudy', lastName: 'Hawkeridge', email: 'thawkeridgef@dion.ne.jp', gender: 'Female', dni: '174-44-7707', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Justine', lastName: 'Kingsnorth', email: 'jkingsnorthg@themeforest.net', gender: 'Female', dni: '730-54-2735', comments: 'primis in faucibus orci luctus et ultrices posuere', createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Lorrie', lastName: 'Cotherill', email: 'lcotherillh@ycombinator.com', gender: 'Male', dni: '659-18-2493', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Joellen', lastName: 'Leasor', email: 'jleasori@jimdo.com', gender: 'Female', dni: '842-74-6302', comments: 'turpis integer', createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Goddard', lastName: 'Senior', email: 'gseniorj@soup.io', gender: 'Male', dni: '686-83-6535', comments: 'nulla', createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Herc', lastName: "De'Vere - Hunt", email: 'hdeverehuntk@google.fr', gender: 'Male', dni: '554-11-8274', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Karim', lastName: 'Deener', email: 'kdeenerl@usda.gov', gender: 'Male', dni: '693-17-0162', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Wain', lastName: 'Bertenshaw', email: 'wbertenshawm@telegraph.co.uk', gender: 'Male', dni: '315-23-8300', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Madel', lastName: 'Warwick', email: 'mwarwickn@cbsnews.com', gender: 'Female', dni: '520-26-2071', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Chico', lastName: 'Chaffin', email: 'cchaffino@yelp.com', gender: 'Male', dni: '131-96-9554', comments: 'enim', createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Leonid', lastName: 'Eouzan', email: 'leouzanp@gov.uk', gender: 'Male', dni: '749-28-4608', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Lemmie', lastName: 'Arkcoll', email: 'larkcollq@cargocollective.com', gender: 'Male', dni: '532-05-4615', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Lisette', lastName: 'Ewbanche', email: 'lewbancher@psu.edu', gender: 'Female', dni: '575-93-9742', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Gayle', lastName: 'Huggins', email: 'ghugginss@surveymonkey.com', gender: 'Male', dni: '815-80-6774', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Veda', lastName: 'Crocetto', email: 'vcrocettot@g.co', gender: 'Female', dni: '685-93-9313', comments: 'et ultrices posuere cubilia curae', createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Karlen', lastName: 'Pattlel', email: 'kpattlelu@nature.com', gender: 'Female', dni: '373-70-0651', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Warner', lastName: 'Roger', email: 'wrogerv@photobucket.com', gender: 'Male', dni: '614-39-8717', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Nicky', lastName: 'Everley', email: 'neverleyw@reddit.com', gender: 'Female', dni: '766-01-1665', comments: 'cubilia curae nulla dapibus dolor', createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Berrie', lastName: 'Reavell', email: 'breavellx@buzzfeed.com', gender: 'Female', dni: '142-12-0423', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Roxanna', lastName: 'Kleinpeltz', email: 'rkleinpeltzy@indiegogo.com', gender: 'Female', dni: '229-75-7786', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Helenka', lastName: 'Kelleway', email: 'hkellewayz@netlog.com', gender: 'Female', dni: '610-87-4049', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Sioux', lastName: 'Dockrell', email: 'sdockrell10@qq.com', gender: 'Female', dni: '493-39-0605', comments: 'volutpat convallis morbi odio odio elementum eu interdum', createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Van', lastName: 'Begwell', email: 'vbegwell11@independent.co.uk', gender: 'Female', dni: '780-73-2284', comments: 'gravida nisi', createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Donal', lastName: 'Coulling', email: 'dcoulling12@github.io', gender: 'Male', dni: '610-65-1704', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Bendix', lastName: 'Vitler', email: 'bvitler13@phpbb.com', gender: 'Male', dni: '515-54-6204', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Darcy', lastName: 'Gouck', email: 'dgouck14@diigo.com', gender: 'Male', dni: '579-70-9033', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Odelinda', lastName: 'Kearns', email: 'okearns15@bigcartel.com', gender: 'Female', dni: '329-70-2565', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Cathy', lastName: 'Dalrymple', email: 'cdalrymple16@biglobe.ne.jp', gender: 'Female', dni: '206-36-3609', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Esmaria', lastName: 'Benley', email: 'ebenley17@ameblo.jp', gender: 'Female', dni: '878-20-7676', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Brandy', lastName: 'Gawthrope', email: 'bgawthrope18@slate.com', gender: 'Male', dni: '869-47-3026', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Auberta', lastName: 'Dalling', email: 'adalling19@cdbaby.com', gender: 'Female', dni: '477-26-5803', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Denna', lastName: 'Menichino', email: 'dmenichino1a@squidoo.com', gender: 'Female', dni: '664-21-1159', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Ella', lastName: 'McRill', email: 'emcrill1b@home.pl', gender: 'Female', dni: '719-65-9595', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Angela', lastName: 'Melonby', email: 'amelonby1c@arizona.edu', gender: 'Female', dni: '790-56-3479', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` },
  { firstName: 'Dianemarie', lastName: 'Cashley', email: 'dcashley1d@twitpic.com', gender: 'Female', dni: '200-46-8262', comments: null, createdAt: `${new Date()}`, updatedAt: `${new Date()}` }];
